# Generated by Django 2.2.4 on 2020-02-15 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('message_time', models.DateTimeField()),
                ('message_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
