# Generated by Django 2.2.3 on 2020-02-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_title', models.CharField(max_length=100)),
                ('query_body', models.CharField(max_length=1000)),
                ('query_created_at', models.DateTimeField()),
                ('query_resolved', models.BooleanField()),
                ('slug', models.SlugField(max_length=40)),
                ('query_city_tag', models.ManyToManyField(blank=True, to='accounts.City')),
                ('query_country_tag', models.ManyToManyField(blank=True, to='accounts.Country')),
                ('query_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('query_resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to='accounts.UserProfile')),
                ('query_school_tag', models.ManyToManyField(blank=True, to='accounts.School')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=5000)),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('post_edited_at', models.DateTimeField(blank=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('post_replies', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=40)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
