# Generated by Django 3.0.4 on 2020-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.CharField(max_length=2000),
        ),
    ]
