# Generated by Django 2.2.3 on 2020-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
