# Generated by Django 3.0.4 on 2020-04-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200424_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askcomment',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='askcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='askcommentlike',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='askcommentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asklike',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asklike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asktagendyear',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asktaghomecountry',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asktaghomecountry',
            name='body',
        ),
        migrations.RemoveField(
            model_name='asktagmajor',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asktagmajor',
            name='body',
        ),
        migrations.RemoveField(
            model_name='asktagschool',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asktagschool',
            name='body',
        ),
        migrations.RemoveField(
            model_name='asktagstartyear',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asktagstatus',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asktagstudyabroadcountry',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='asktagstudyabroadcountry',
            name='body',
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
        migrations.DeleteModel(
            name='AskComment',
        ),
        migrations.DeleteModel(
            name='AskCommentLike',
        ),
        migrations.DeleteModel(
            name='AskLike',
        ),
        migrations.DeleteModel(
            name='AskTagEndYear',
        ),
        migrations.DeleteModel(
            name='AskTagHomeCountry',
        ),
        migrations.DeleteModel(
            name='AskTagMajor',
        ),
        migrations.DeleteModel(
            name='AskTagSchool',
        ),
        migrations.DeleteModel(
            name='AskTagStartYear',
        ),
        migrations.DeleteModel(
            name='AskTagStatus',
        ),
        migrations.DeleteModel(
            name='AskTagStudyAbroadCountry',
        ),
    ]
