# Generated by Django 2.2.4 on 2020-02-21 06:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=200)),
                ('school_start_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1940)])),
                ('school_end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1940)])),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_job', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_job_start_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1970)])),
                ('previous_job_end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1970)])),
                ('post_job', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('future', 'future'), ('student', 'student'), ('alumni', 'alumni')], max_length=20)),
                ('follower', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=40)),
                ('living_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.City')),
                ('living_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country')),
                ('school', models.ManyToManyField(to='account.School')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Country'),
        ),
    ]
