# Generated by Django 3.0.4 on 2020-04-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_study_abroad',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudyAbroad',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('education', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Education')),
            ],
        ),
    ]
