# Generated by Django 3.0.4 on 2020-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200426_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('P', 'PhD'), ('O', 'Others')], default='B', max_length=30),
        ),
    ]
