# Generated by Django 3.0.4 on 2020-04-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200403_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
