# Generated by Django 3.0.4 on 2020-03-31 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200331_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='living_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.City'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
