# Generated by Django 3.0.4 on 2020-03-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200331_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='studyinterest',
            old_name='field',
            new_name='body',
        ),
    ]
