# Generated by Django 3.0.4 on 2020-04-07 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0004_auto_20200405_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_image', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
