# Generated by Django 3.0.4 on 2020-04-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20200401_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-end_year']},
        ),
        migrations.AddField(
            model_name='workexperience',
            name='status',
            field=models.CharField(choices=[('P', 'I worked at this company'), ('C', 'I am currently working at this company'), ('T', 'This is my target company')], default='P', max_length=30),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(blank=True, max_length=20, null=True)),
                ('end_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_present', models.BooleanField()),
                ('school', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('C', 'I am currently studying at this school'), ('P', 'I studied at this school'), ('F', 'I am going to study at this school'), ('T', 'This is my target school')], default='C', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_year'],
                'abstract': False,
            },
        ),
    ]
