# Generated by Django 3.0.4 on 2020-04-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200402_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='education',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='status',
        ),
    ]
