# Generated by Django 3.0.4 on 2020-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200417_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
