# Generated by Django 3.0.4 on 2020-04-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200403_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year', '-start_year']},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['-end_year', '-start_year']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-end_year', '-start_year']},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='year_to',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='end_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='start_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
