# Generated by Django 2.2.10 on 2020-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='job_after_abroad_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='job_before_abroad_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='year_of_abroad_study',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
