# Generated by Django 3.0.4 on 2020-03-26 22:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20200314_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LN', 'LinkedIn'), ('IG', 'Instagram'), ('BL', 'Blog')], max_length=20)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('start_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1970)])),
                ('end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1970)])),
                ('is_present', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='job_after_abroad_study',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='job_before_abroad_study',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='school',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='baseinfo',
            name='year_of_abroad_study',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_message_read_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='living_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='post_job',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='previous_job',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='previous_job_end_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='previous_job_start_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Genderqueer/Non-Binary'), ('NA', 'Prefer not to disclose')], default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_study_abroad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('FU', 'Future Student'), ('CU', 'Current Student'), ('AL', 'Alumni')], default='CU', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_end_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(1940)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1940)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
