version: '3.7'

services:
    # web:
    #     build: ./app
    #     command: python manage.py runserver 0.0.0.0:8000
    #     volumes:
    #     - ./app/:/usr/src/app/
    #     ports:
    #     - 8000:8000
    #     env_file:
    #     - ./env/.env.dev
    #     depends_on:
    #         - db
    api:
        build: ./backend
        command: python manage.py runserver 0.0.0.0:6000
        volumes:
        - ./backend/:/usr/src/backend/
        ports:
        - 6000:6000
        env_file:
        - ./env/.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./env/.db.env.dev
        
volumes:
    postgres_data: