version: '3.7'

services:
  web:
    image: alumate/production:web
    command: gunicorn alumate.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    environment:
        - DEBUG=1
        - SECRET_KEY=!f7!huaaiut+_wo+n_zl3jpq&$qp5kv!x^2c&af%8d7&c5k*w)
        - SQL_ENGINE=django.db.backends.postgresql
        - SQL_DATABASE=alumate_prod
        - SQL_USER=alumate
        - SQL_PASSWORD=StudyAbroad
        - SQL_HOST=db
        - SQL_PORT=5432
        - DATABASE=postgres
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
        - POSTGRES_USER=alumate
        - POSTGRES_PASSWORD=StudyAbroad
        - POSTGRES_DB=alumate_prod

  nginx:
    image: alumate/production:nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: