# Generated by Django 2.2.4 on 2020-02-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0008_auto_20200210_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_title', models.CharField(max_length=100)),
                ('query_body', models.CharField(max_length=1000)),
                ('query_created_at', models.DateTimeField(auto_now_add=True)),
                ('query_resolved', models.BooleanField()),
                ('query_resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.UserProfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_creator', to='user_profile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=5000)),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('post_edited_at', models.DateTimeField(blank=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('post_replies', models.IntegerField(default=0)),
                ('slug', models.CharField(max_length=100)),
                ('post_city_tag', models.ManyToManyField(to='user_profile.City')),
                ('post_country_tag', models.ManyToManyField(to='user_profile.Country')),
                ('post_school_tag', models.ManyToManyField(to='user_profile.School')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.UserProfile')),
            ],
        ),
    ]
