# Generated by Django 2.2.4 on 2020-02-21 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_title', models.CharField(max_length=100)),
                ('query_body', models.CharField(max_length=1000)),
                ('query_created_at', models.DateTimeField()),
                ('query_resolved', models.BooleanField()),
                ('query_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=5000)),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('post_edited_at', models.DateTimeField(blank=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('post_views', models.IntegerField(default=0)),
                ('post_replies', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=40)),
                ('post_city_tag', models.ManyToManyField(to='people.City')),
                ('post_country_tag', models.ManyToManyField(to='people.Country')),
                ('post_school_tag', models.ManyToManyField(to='people.School')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
