# Generated by Django 2.2.4 on 2020-02-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_city_tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_country_tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_school_tag',
        ),
    ]
