# Generated by Django 2.2.4 on 2020-02-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20200210_0644'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query_resolved_by',
        ),
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.AddField(
            model_name='query',
            name='query_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.UserProfile'),
        ),
    ]
