# Generated by Django 2.2.4 on 2020-02-21 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '__first__'),
        ('post', '0002_auto_20200221_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to='people.UserProfile'),
        ),
    ]
