# Generated by Django 2.2.4 on 2020-02-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_query_query_resolved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to='people.UserProfile'),
        ),
    ]
