# Generated by Django 3.0.4 on 2020-04-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askcommentlike',
            old_name='ask',
            new_name='comment',
        ),
    ]
