# Generated by Django 2.2.3 on 2020-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_baseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='year_of_abroad_study',
            field=models.CharField(max_length=15),
        ),
    ]
