# Generated by Django 2.2.3 on 2020-03-01 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200301_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
