# Generated by Django 2.2.4 on 2020-02-21 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_city_tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_country_tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_school_tag',
        ),
        migrations.AddField(
            model_name='query',
            name='query_city_tag',
            field=models.ManyToManyField(blank=True, to='account.City'),
        ),
        migrations.AddField(
            model_name='query',
            name='query_country_tag',
            field=models.ManyToManyField(blank=True, to='account.Country'),
        ),
        migrations.AddField(
            model_name='query',
            name='query_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to='account.UserProfile'),
        ),
        migrations.AddField(
            model_name='query',
            name='query_school_tag',
            field=models.ManyToManyField(blank=True, to='account.School'),
        ),
        migrations.AddField(
            model_name='query',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
