# Generated by Django 2.2.4 on 2020-02-21 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200221_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
