# Generated by Django 2.2.3 on 2020-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200301_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
