# Generated by Django 2.2.3 on 2020-03-01 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200301_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
