# Generated by Django 2.2.3 on 2020-02-06 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=200)),
                ('school_start_year', models.IntegerField(default=1975, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1940)])),
                ('school_end_year', models.IntegerField(default=2005, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1940)])),
                ('course', models.CharField(max_length=50)),
                ('previus_job', models.CharField(max_length=100)),
                ('previus_job_start_year', models.IntegerField(default=2005, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1970)])),
                ('previus_job_end_year', models.IntegerField(default=2010, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1970)])),
                ('living_country', models.CharField(max_length=50)),
                ('living_city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('preparing', 'preparing'), ('student', 'student'), ('alumni', 'alumni')], max_length=20)),
                ('follower', models.IntegerField()),
                ('following', models.IntegerField()),
                ('posts', models.IntegerField()),
                ('school', models.ManyToManyField(to='user_profile.School')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
