# Generated by Django 2.2.4 on 2020-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='previus_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
