# Generated by Django 2.2.4 on 2020-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20200210_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
